### ISSUE TITLE
create hero section component (about)

### ISSUE THREAD

**Issue by JeremiahKW** [Summit-DevLabs/motion-hive#17]

**Comment by JeremiahKW** [comment]
![Image](https://github.com/user-attachments/assets/7cea0d9d-9afc-4d4c-8a41-aa1b55103fbe)
Reference penpot and about pages "dark" to create this component

**Comment by shawnwilson88** [comment]
@JeremiahKW do you have a link to the tailwind component you pulled this from?

**Comment by JeremiahKW** [comment]
In the description it says About Pages - Dark, I'd search that in tailwind. I don't have the link with me though, sorry

**Comment by JeremiahKW** [comment]
@JazzyBiscuit88 ^
