### ISSUE TITLE
create divider component (homepage)

### ISSUE THREAD

**Issue by JeremiahKW** [Summit-DevLabs/motion-hive#8]

**Comment by JeremiahKW** [comment]
![Image](https://github.com/user-attachments/assets/ff7c2af2-076b-4430-aea5-02c26f5cefbe)

Create custom component or use divider with centered label from tailwind components

**Comment by jwalls505** [comment]
![Image](https://github.com/user-attachments/assets/2bf1c63c-1dfb-4826-a263-af697c0a2fda)


@JeremiahKW
